/* Search index for the Khuwari docs. The hub (docs.html) searches across every
 * category page through this list; each topic links to its subpage. */
window.KHUWARI_DOCS = [
  // ---- getting started ----
  { cat: 'Getting started', slug: 'getting-started', id: 'what-is', title: 'What is Khuwari?',
    text: 'Khuwari is a browser based animation tool that fills in the frames between your keyframes using machine learning. You draw or import the important poses, place them on the timeline, and Khuwari generates everything in between. It runs entirely in your browser. The machine learning model is downloaded once, and your art never leaves your machine.',
    url: 'docs/getting-started.html' },
  { cat: 'Getting started', slug: 'getting-started', id: 'open-app', title: 'Open the app',
    text: 'Serve the project folder with any static file server and open index.html. From the start screen you can start a new project, load an existing .khuwari file, or try the bundled example project. The example project is the fastest way to see what a finished animation looks like. Load it and press play.',
    url: 'docs/getting-started.html' },
  { cat: 'Getting started', slug: 'getting-started', id: 'project-files', title: 'Project files',
    text: 'Projects save as .khuwari files. They are plain JSON files that hold your layers, keyframes, gaps and settings, so they are easy to version and share. Use File in the toolbar, then Save project (.khuwari) to download one, and Load project to bring one back.',
    url: 'docs/getting-started.html' },

  // ---- interface ----
  { cat: 'The interface', slug: 'interface', id: 'assets-panel', title: 'Assets panel',
    text: 'Your image library, on the left. Use Add images to bring in art, then drag images onto the timeline to make keyframes. You can delete images from the panel when you no longer need them.',
    url: 'docs/interface.html' },
  { cat: 'The interface', slug: 'interface', id: 'preview', title: 'The preview',
    text: 'The large canvas in the center shows the current frame, and the filmstrip under it shows every frame of the animation. Press play to watch it move, or step frame by frame with the arrow keys.',
    url: 'docs/interface.html' },
  { cat: 'The interface', slug: 'interface', id: 'timeline', title: 'The timeline',
    text: 'Each layer has its own track at the bottom. Keyframes appear as chips, and the space between two keyframes is a gap. Click a chip to select it, drag it to move it, and drag its edges to change how long it holds.',
    url: 'docs/interface.html' },
  { cat: 'The interface', slug: 'interface', id: 'selection-panel', title: 'Selection panel',
    text: 'Shows the details of whatever you have selected, whether that is a keyframe, a gap or a color dot. This is where you set times, blend modes, interpolation and dot properties.',
    url: 'docs/interface.html' },
  { cat: 'The interface', slug: 'interface', id: 'layers', title: 'Layers',
    text: 'The Layer button in the toolbar opens the layer menu. From there you can add a normal layer, add a color layer, rename, hide or remove the active layer. Layers draw from top to bottom, and each one keeps its own keyframes and gaps. Drag layers up and down in the menu to reorder them.',
    url: 'docs/interface.html' },

  // ---- keyframes ----
  { cat: 'Keyframes', slug: 'keyframes', id: 'add-keyframe', title: 'Add a keyframe',
    text: 'Drag an image from the assets panel onto a layer track at the time you want it. The image becomes a keyframe chip that holds that pose.',
    url: 'docs/keyframes.html' },
  { cat: 'Keyframes', slug: 'keyframes', id: 'select-inspect', title: 'Select and inspect',
    text: 'Click a chip to select it. The selection panel on the right shows a thumbnail, the exact time, the blend mode, and buttons to replace or delete the frame.',
    url: 'docs/keyframes.html' },
  { cat: 'Keyframes', slug: 'keyframes', id: 'move-resize', title: 'Move and resize',
    text: 'Drag a chip left or right to change when it happens. Drag its edges to change how long the frame holds before the gap starts. Hold times matter for pacing.',
    url: 'docs/keyframes.html' },
  { cat: 'Keyframes', slug: 'keyframes', id: 'set-time', title: 'Set the time exactly',
    text: 'With a keyframe selected, enter the time in seconds in the selection panel. Use the playhead and frame counter to find the moment you want.',
    url: 'docs/keyframes.html' },
  { cat: 'Keyframes', slug: 'keyframes', id: 'replace-delete', title: 'Replace or delete',
    text: 'Select a keyframe and use Replace image to swap in different art, or Delete to remove it. The keyboard shortcut Delete or Backspace also works.',
    url: 'docs/keyframes.html' },

  // ---- gaps & interpolation ----
  { cat: 'Gaps & interpolation', slug: 'gaps', id: 'what-is-gap', title: 'What is a gap?',
    text: 'The space between two keyframes on the same layer. Click the gap chip on the timeline to open its options in the right panel. The inbetweens are generated there.',
    url: 'docs/gaps.html' },
  { cat: 'Gaps & interpolation', slug: 'gaps', id: 'ml', title: 'Machine learning',
    text: 'The default mode. A machine learning model generates the inbetween frames, which gives the most natural motion for complex art. This is where Khuwari shines.',
    url: 'docs/gaps.html' },
  { cat: 'Gaps & interpolation', slug: 'gaps', id: 'squash', title: 'Squash and stretch',
    text: 'A stylized deformation for cartoon motion. Choose the amount, the curve (anticipation, impact, ease or linear) and whether to preserve area or volume. Set the amount to auto for a distance based value.',
    url: 'docs/gaps.html' },
  { cat: 'Gaps & interpolation', slug: 'gaps', id: 'none', title: 'No interpolation',
    text: 'No inbetweens at all. The first keyframe simply holds until the next one starts. Good for flashes, cuts and text.',
    url: 'docs/gaps.html' },
  { cat: 'Gaps & interpolation', slug: 'gaps', id: 'motion-blur', title: 'Motion blur',
    text: 'A per gap toggle. When on, the inbetweens smear along their motion, and the blur eases in and out with the movement. The intensity slider controls how strong the smear is. It is designed to mask small imperfections in generated frames, and it works on color layers too.',
    url: 'docs/gaps.html' },
  { cat: 'Gaps & interpolation', slug: 'gaps', id: 'regenerate', title: 'Regenerate',
    text: 'Inbetweens regenerate automatically whenever your keyframes change. To force a full refresh, use the regenerate button above the timeline, to the right of the play buttons.',
    url: 'docs/gaps.html' },

  // ---- color layers ----
  { cat: 'Color layers', slug: 'color-layers', id: 'what-they-do', title: 'What they do',
    text: 'A color layer holds dots instead of keyframes. Each dot acts like a smart bucket fill for the layer above it, so you can color in line art without touching the drawing.',
    url: 'docs/color-layers.html' },
  { cat: 'Color layers', slug: 'color-layers', id: 'add-place', title: 'Add one and place dots',
    text: 'Use the Layer menu and choose Add color layer. Then click on the canvas to place a dot. The dot fills everything inside the nearest lines of the layer above.',
    url: 'docs/color-layers.html' },
  { cat: 'Color layers', slug: 'color-layers', id: 'dot-properties', title: 'Dot properties',
    text: 'Each dot has a fill color, a threshold (how strong a line must be to stop the fill) and a grow radius in pixels, which tucks the color under anti-aliased edges. Tune these per dot.',
    url: 'docs/color-layers.html' },
  { cat: 'Color layers', slug: 'color-layers', id: 'gradients', title: 'Gradients',
    text: 'Turn on Gradient to give a dot a gradient instead of a flat fill. Choose the gradient color, its height and its direction (top, bottom, left or right).',
    url: 'docs/color-layers.html' },
  { cat: 'Color layers', slug: 'color-layers', id: 'timing', title: 'Timing',
    text: 'Dots only work during the time you set. Use the start and end fields in the right panel, or drag the dot chip on the timeline and drag its edges to resize. Outside that window the dot does nothing.',
    url: 'docs/color-layers.html' },
  { cat: 'Color layers', slug: 'color-layers', id: 'stacking', title: 'Stacking',
    text: 'Dots that overlap in time stack into their own rows in the timeline, so they never cover each other and stay easy to find. The color layer grows to fit the stack, no matter how many dots overlap.',
    url: 'docs/color-layers.html' },

  // ---- onion skinning ----
  { cat: 'Onion skinning', slug: 'onion-skinning', id: 'what-it-is', title: 'What it is',
    text: 'Onion skinning shows the frames around the current one, so you can see where the motion is heading while you work. It is a toggle, like the view only keyframes button.',
    url: 'docs/onion-skinning.html' },
  { cat: 'Onion skinning', slug: 'onion-skinning', id: 'turn-it-on', title: 'Turn it on',
    text: 'The onion button in the transport area toggles it on and off. The small arrow next to it opens the settings popup.',
    url: 'docs/onion-skinning.html' },
  { cat: 'Onion skinning', slug: 'onion-skinning', id: 'settings', title: 'Settings',
    text: 'Choose how many frames to show before and after the current one, the ghost opacity, and whether to show ghosts tinted. If you enable tint, pick the tint color and strength.',
    url: 'docs/onion-skinning.html' },
  { cat: 'Onion skinning', slug: 'onion-skinning', id: 'saved', title: 'Saved automatically',
    text: 'Your onion skin settings are saved in the browser, so they come back the next time you open Khuwari, even after loading a project.',
    url: 'docs/onion-skinning.html' },

  // ---- blend modes ----
  { cat: 'Blend modes', slug: 'blend-modes', id: 'per-keyframe', title: 'Per keyframe blending',
    text: 'Each keyframe can use any of 16 blend modes, from multiply and screen to color and luminosity. Set it in the selection panel with a keyframe selected. Inbetweens between two keyframes use the normal blend, so the blending itself stays stable across the gap.',
    url: 'docs/blend-modes.html' },

  // ---- export ----
  { cat: 'Export', slug: 'export', id: 'formats', title: 'Formats',
    text: 'The Export button in the toolbar offers four formats: a PNG sequence in a zip, an animated GIF, an MP4 video, and the current frame as a single PNG.',
    url: 'docs/export.html' },
  { cat: 'Export', slug: 'export', id: 'resolution', title: 'Resolution',
    text: 'Pick the export resolution from the export menu. Exports run in the background with a progress bar, and you can stop them if you change your mind.',
    url: 'docs/export.html' },
  { cat: 'Export', slug: 'export', id: 'wysiwyg', title: 'What you see is what you get',
    text: 'Exports render through the same composite as playback, so the video, GIF and sequence all match what you see in the preview, including blend modes and color fills.',
    url: 'docs/export.html' },

  // ---- settings ----
  { cat: 'Settings', slug: 'settings', id: 'fps', title: 'FPS',
    text: 'How many frames per second the timeline plays. Lower values are punchier and cheaper to generate, higher values are smoother.',
    url: 'docs/settings.html' },
  { cat: 'Settings', slug: 'settings', id: 'snap', title: 'Snap to frames',
    text: 'Keeps the playhead and keyframes on whole frames, so times stay tidy. Turn it off for free placement.',
    url: 'docs/settings.html' },
  { cat: 'Settings', slug: 'settings', id: 'aspect', title: 'Aspect ratio',
    text: 'Follow the first frame, pick a preset such as 16:9 or 1:1, or set a custom size or a manual ratio like 2.35.',
    url: 'docs/settings.html' },
  { cat: 'Settings', slug: 'settings', id: 'work-size', title: 'Working size',
    text: 'The long edge of the working canvas, from 512 pixels down to 320. Smaller is noticeably faster to generate, and exports still render at full resolution.',
    url: 'docs/settings.html' },

  // ---- keyboard shortcuts ----
  { cat: 'Keyboard shortcuts', slug: 'shortcuts', id: 'playback', title: 'Playback',
    text: 'Space plays or pauses the animation. Left and Right arrows step one frame back or forward.',
    url: 'docs/shortcuts.html' },
  { cat: 'Keyboard shortcuts', slug: 'shortcuts', id: 'editing', title: 'Editing',
    text: 'Delete or Backspace deletes the selected keyframe. Shortcuts are ignored while you are typing in a field.',
    url: 'docs/shortcuts.html' },

  // ---- privacy ----
  { cat: 'Privacy', slug: 'privacy', id: 'nothing-leaves', title: 'Nothing leaves your browser',
    text: 'Khuwari is a local, serverless tool. The machine learning model downloads once and then runs in your browser, and your images, projects and exports never leave your machine. There are no accounts and no tracking.',
    url: 'docs/privacy.html' }
];
